## numpy 组合数组

### 相关函数

vstack

dstack

hstack

column_stack

row_stack

concatenate

## hstack函数


In [3]:
import numpy as np
a = np.arange(9).reshape(3,3)
b = a*2

np.hstack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

## concatenate函数

In [4]:
# axis = 0代表行排列，axis = 1代表列排列
np.concatenate((a,b),axis=0) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

## vstack函数

In [6]:
np.vstack((a,b))             # 行排列

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

## dstack函数

In [7]:
np.dstack((a,b))  #纵向 

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

## column_stack函数

In [8]:
# 对于二维数组，column_stack与hstack的效果是相同
np.column_stack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [9]:
a = np.arange(3)
b = np.arange(3)
# column_stack函数对于一维数组将按列方向进行组
np.column_stack((a,b)) 

array([[0, 0],
       [1, 1],
       [2, 2]])

## row_stack 函数

In [10]:
# 行组合
# 对于两个一维数组，将直接层叠起来组合成一个二维数组。
np.row_stack((a,b))  

array([[0, 1, 2],
       [0, 1, 2]])